Added MemoryStore shutdown method
nfriedly/express-rate-limit pull request #322
Opened 2022-08-29 16:53 UTC by codyebberson

## Related Issues

Fixes https://github.com/nfriedly/express-rate-limit/issues/320

## What Does This PR Do?

### Added

Added `MemoryStore.shutdown` which clears the timer and allows applications to completely stop a running instance of MemoryStore.

## Checklist

- [x] The issues that this PR fixes/closes have been mentioned above.
- [x] What this PR adds/changes/removes has been explained.
- [x] All tests (`npm test`) pass.
- [x] All added/modified code has been commented, and
      methods/classes/constants/types have been annotated with TSDoc comments.
- [x] If a new feature has been added or a bug has been fixed, tests have been
      added for the same.

2022-08-30 12:33 UTC, gamemaker1 commented
This looks great! Could you please also add the shutdown method to the `Store` interface in `source/types.ts` too? That way other stores can add it too.

2022-08-30 13:34 UTC, nfriedly commented
Could you please also add the shutdown method to the Store interface in source/types.ts too?

That's a good idea! We should make it optional, though I don't want other stores to be required to implement it. Also, it should probably be `async` so that stores where the shut down is not instantaneous can indicate when it's complete.

2022-08-30 13:39 UTC, codyebberson commented
Can do.  Something like this?

`shutdown?: () => Promise<void> | void`

2022-08-31 03:32 UTC, gamemaker1 commented
This is great!

Sorry I didn't mention this earlier, but I think we should add an external test for this too - adding a shutdown method that prints 'Shutdown successful' (to the store [here](https://github.com/nfriedly/express-rate-limit/blob/0361f4cb9fce25e08a65ad637918c2bd45da9976/test/external/imports/default-import/ts-esm/source/app.ts#L11)) and call the function when a request is received ([here](https://github.com/nfriedly/express-rate-limit/blob/0361f4cb9fce25e08a65ad637918c2bd45da9976/test/external/imports/default-import/ts-esm/source/app.ts#L44)); and then make the same changes to [this](https://github.com/nfriedly/express-rate-limit/blob/0361f4cb9fce25e08a65ad637918c2bd45da9976/test/external/imports/named-import/ts-esm/source/app.ts) file too.

We should also add documentation about the shutdown method to the [wiki](https://github.com/nfriedly/express-rate-limit/wiki/Creating-Your-Own-Store).

After that, this PR should be good to go!

2022-08-31 03:44 UTC, NoahAndrews commented
Do we need the ` | void`? I'd have thought the question mark was enough.

2022-08-31 04:55 UTC, codyebberson commented
@gamemaker1 Of course.

> call the function when a request is received

I'm not sure I understand.  Call the `shutdown` method from inside the request?

@NoahAndrews 

> Do we need the | void? I'd have thought the question mark was enough.

The `| void` applies to the return type of the optional method, meaning that `shutdown` can return a `Promise<void>` or `void`.  I'm happy to change it to simply always return a `Promise<void>`.

2022-08-31 05:53 UTC, gamemaker1 commented
> I'm not sure I understand. Call the shutdown method from inside the request?

Oof I realise that's really silly to do, sorry about that. I think a better way would be:

- first add a `shutdown` method to the `TestStore` [here](https://github.com/nfriedly/express-rate-limit/blob/0361f4cb9fce25e08a65ad637918c2bd45da9976/test/external/imports/default-import/ts-esm/source/app.ts#L31) that prints `test-store: shutdown successful`.
- then export a `store` variable (with [this](https://github.com/nfriedly/express-rate-limit/blob/0361f4cb9fce25e08a65ad637918c2bd45da9976/test/external/imports/default-import/ts-esm/source/app.ts#L40) value) from `source/app.ts`.
- then call the `shutdown` function on the store once all the test requests are made ([here](https://github.com/nfriedly/express-rate-limit/blob/0361f4cb9fce25e08a65ad637918c2bd45da9976/test/external/imports/default-import/ts-esm/test/server-test.ts#L12)), and check that the message `test-store: shutdown successful` has been printed if the store was an instance of `TestStore`. If not, we don't need to check as the memory store's shutdown method is already checked by the library tests.

You would also need to do the same for the `named-import` external test for `ts-esm` [here](https://github.com/nfriedly/express-rate-limit/tree/0361f4cb9fce25e08a65ad637918c2bd45da9976/test/external/imports/named-import/ts-esm).

> The | void applies to the return type of the optional method, meaning that shutdown can return a Promise<void> or void. I'm happy to change it to simply always return a Promise<void>.

Please keep the `| void`, it allows the function to be synchronous. If the function's allowed return type is only `Promise<void>`, then it forces the function to be asynchronous.

2022-09-01 15:40 UTC, gamemaker1 commented
This looks good to go!

@nfriedly what do you think?

2022-09-01 20:40 UTC, nfriedly requested changes
Thanks, this is great work!  Sorry I've been out of the loop for a couple of days.

I think we should make the test call `expect(setTimeout).toHaveBeenCalledWith(...);` but the other things I mentioned are minor points that don't necessarily need to be changed.

2022-09-02 16:58 UTC, codyebberson commented on test/library/memory-store-test.ts
> +		expect(store.interval).toBeUndefined()
@nfriedly Done

2022-09-02 16:59 UTC, codyebberson commented on source/memory-store.ts
> +			this.interval = undefined
@nfriedly Done

2022-09-04 06:27 UTC, gamemaker1 approved these changes
LGTM!

2022-09-04 19:01 UTC, nfriedly approved these changes
Thank you, this is a good addition! I'll get a release out shortly.

2022-09-04 19:01 UTC, merged